FROM python

# Set environment variables
# ENV PYTHONUNBUFFERED 1

# Create and set the working directory
WORKDIR /app

# Copy only the necessary files
COPY Recommender-Final.py model_Stacking.joblib requirements.txt /app/

# Upgrade pip and install needed packages
RUN pip install --no-cache-dir -r requirements.txt 


# Make port 5000 available to the world outside this container
EXPOSE 5000

# Specify the command to run your script (modify as needed)
CMD ["python", "Recommender-Final.py"]